# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('accelerators', '0001_initial'), ('accelerators', '0002_auto_20151006_1658'), ('accelerators', '0003_auto_20151007_1926'), ('accelerators', '0004_auto_20151013_1415'), ('accelerators', '0005_auto_20151020_1027'), ('accelerators', '0006_cohort_watchers'), ('accelerators', '0007_auto_20151020_1922'), ('accelerators', '0008_auto_20151113_0219'), ('accelerators', '0009_middlewatcher'), ('accelerators', '0010_auto_20160317_1243'), ('accelerators', '0011_auto_20170220_1513'), ('accelerators', '0012_auto_20170303_0937')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accelerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('accelerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='accelerators.Accelerator')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together=set([('name', 'accelerator')]),
        ),
    ]
