# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerators', '0001_squashed_0012_auto_20170303_0937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together=set([]),
        ),
    ]
